# Generated by Django 4.2.1 on 2023-05-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=20, unique=True)),
                ("role", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="userreg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("disability", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=10)),
                ("userstatus", models.CharField(max_length=10)),
                (
                    "login_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="disabled.log"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=20)),
                ("workstatus", models.CharField(max_length=20)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disabled.userreg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="shopreg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("shopstatus", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=10)),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="disabled.log"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("date", models.DateField(max_length=20)),
                ("worker_name", models.CharField(max_length=20)),
                ("user_contact", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disabled.userreg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=20)),
                ("product_rate", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="images")),
                ("description", models.CharField(max_length=80)),
                ("size", models.CharField(max_length=20)),
                ("color", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disabled.shopreg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("product_name", models.CharField(max_length=20)),
                ("date", models.DateField(max_length=20)),
                ("total_amount", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disabled.userreg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("product_name", models.CharField(max_length=20)),
                ("quantity", models.CharField(max_length=20)),
                ("total_price", models.CharField(max_length=20)),
                ("date", models.DateField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disabled.userreg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification", models.CharField(max_length=30)),
                ("date", models.DateField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disabled.shopreg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("feedback", models.CharField(max_length=30)),
                ("date", models.DateField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disabled.userreg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="counciling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counciling_type", models.CharField(max_length=30)),
                ("date", models.DateField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disabled.userreg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="complaints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("complaints", models.CharField(max_length=30)),
                ("date", models.DateField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disabled.userreg",
                    ),
                ),
            ],
        ),
    ]
